### ISSUE TITLE
IDs potentially getting re-used?

### ISSUE THREAD

**Issue by archanyhm** [keyraven/ClanGen-CSharp#1]
https://github.com/keyraven/ClanGen-CSharp/blob/f155ae5f56ee7b8cec15dd9b49b8d7d0bfccd882/Clangen/Models/CatGroups/Group.cs#L23C4-L45C1

This is going to cause some trouble down the line. You usually _never_ want to reassign identifiers in any case + this approach is "slow". I'd suggest the very same approach that most RDBMS use when assigning sequential identifiers by storing the last ID somewhere persistently (on a per-clan basis) and just incrementing it each time a new ID is needed. Hitting any tangible limits that way is _incredibly_ unlikely + it's slightly faster + it's safer.

**Comment by keyraven** [comment]
The lastID is now stored on the world-level, and simply incremented whenever a new ID is generated.
