### ISSUE TITLE
Stateful constructor with no parameters

### ISSUE THREAD

**Issue by archanyhm** [keyraven/ClanGen-CSharp#2]
https://github.com/keyraven/ClanGen-CSharp/blob/f155ae5f56ee7b8cec15dd9b49b8d7d0bfccd882/Clangen/Models/CatGroups/Group.cs#L9

This one is a bit dangerous. It's usually _never_ advisable to have constructors rely on static state of some other class; even if it's the very own class. This makes the behaviour of the constructors non-deterministic, since it depends on the state of the (static) number generator. It's _much_ more advisable to have a non-static ID generator class that handles ID generation and pass the generated ID into the constructor of this class, and probably others that exhibit similar behaviours.

Just for the record: Non-deterministic constructors can ruin your day quite easily.

**Comment by keyraven** [comment]
This is a fair point. I will refactor this to require IDs be passed to the constructor.
